### ISSUE TITLE
on Windows 10 pro docker-compose run --service-ports web returning error

### ISSUE THREAD

**Issue by pyrobit** [jor3scobar/pets-api#1]
Hi following the readme instructions I am getting the following error related to manage.py I already checked the file location and content is OK.
I am using windows 10 pro
Docker version 18.09.2, build 6247962
Python 3.7.3

I did not alter anything from the files in your repo. 
And I am running the command prompt as administrator (to eliminate chances of permission issue)

Error output:
I:\_docker-projs\orig-pets-api\pets-api>docker-compose up -d db
Creating petsapi_db_1 ... done

I:\_docker-projs\orig-pets-api\pets-api>docker-compose run --service-ports web
Starting petsapi_db_1 ... done
python: can't open file 'manage.py': [Errno 2] No such file or directory

**Comment by esfoobar** [comment]
Hi @pyrobit. This happens when the local path in your machine doesn't match with the path on the Docker Compose YML ([see here](https://github.com/esfoobar/pets-api/blob/master/docker-compose.yml#L8)). 

If you are running the command from inside the directory, you can try doing the `volumes` like this:

```
    volumes:
      - ./:/opt/pets-api
```

Let me know if that works.

**Comment by pyrobit** [comment]
> Hi @pyrobit. This happens when the local path in your machine doesn't match with the path on the Docker Compose YML ([see here](https://github.com/esfoobar/pets-api/blob/master/docker-compose.yml#L8)).
> 
> If you are running the command from inside the directory, you can try doing the `volumes` like this:
> 
> ```
>     volumes:
>       - ./:/opt/pets-api
> ```
> 
> Let me know if that works.

It worked, Thanks! 
I was trying to enable a setting called COMPOSE_CONVERT_WINDOWS_PATHS, but your approach was easier :)
